FROM debian:latest

ENV SCAPY_USE_LIBPCAP="yes"
ENV VERSION=1.7.7

RUN apt-get update && apt-get install -y \
    python3 python3-scapy vlc sudo

ENV HOME=/home/vlc
RUN groupadd -f video && \
    useradd -m -d $HOME vlc && \
    usermod -aG video,sudo vlc && \
    echo "vlc ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vlc && \
    chmod 0440 /etc/sudoers.d/vlc

WORKDIR $HOME
COPY . /home/vlc
RUN chown -R vlc:vlc $HOME

USER vlc
CMD [ "tail", "-f", "/dev/null" ]